### ISSUE TITLE
Licensing Terms

### ISSUE THREAD

**Issue by VeitSanner** [wbaer/FileChecker#1]
Hi Bill,

I really like your FileChecker sample code. However, I am a little bit unclear about the licensing terms. I can't see any file about the licensing model you provide this software under. 

Looking at the azure repositories, they seem to distribute their samples under the MIT license. E.g. [Azure/azure-quickstart-templates](https://github.com/Azure/azure-quickstart-templates/blob/master/LICENSE)

Best regards,

Veit

**Comment by wbaer** [comment]
Shared under MIT License https://github.com/wbaer/FileChecker/blob/master/LICENSE.
